version: '3'

services:
  nginx:
    build: docker/nginx
    ports:
      - 8081:80
    depends_on:
      - php
    volumes:
      - ./:/var/www/symfony
      - ./logs/nginx/:/var/log/nginx

  php:
    build: docker/php-fpm
    volumes:
      - ./:/var/www/symfony
      - ./logs/symfony:/var/www/symfony/var/logs

  frontend:
    build: docker/frontend
    volumes:
      - ./:/var/www/html