version: '3'

services:
  nginx:
    build: docker/nginx
    ports:
      - 8080:80
    depends_on:
      - php
    volumes:
      - ./:/var/www/symfony
      - ./logs/nginx/:/var/log/nginx

  php:
    build: docker/php-fpm
    ports:
      - 9002:9000
    volumes:
      - ./:/var/www/symfony
      - ./logs/symfony:/var/www/symfony/var/logs
    depends_on:
      - mysql
      - redis
      - rabbitmq

  frontend:
    build: docker/frontend
    volumes:
      - ./:/var/www/html